In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
B = [[4, 5, 6], [7, 8, 9]]

In [4]:
I = [[1, 0], [0, 1]]
C = [[1, 2], [3, 4]]

In [5]:
I + C

[[1, 0], [0, 1], [1, 2], [3, 4]]

In [8]:
I = np.array([[1, 0], [0, 1]])
C = np.array([[1, 2], [3, 4]])

In [9]:
I + C

array([[2, 2],
       [3, 5]])

In [10]:
I

array([[1, 0],
       [0, 1]])

In [18]:
C

array([[1, 2],
       [3, 4]])

In [13]:
a = np.array([1, 2, 3])
b = np.array([-3, -2, -1])
a + b

array([-2,  0,  2])

In [14]:
3 * a

array([3, 6, 9])

In [15]:
a * b

array([-3, -4, -3])

In [16]:
np.dot(a, b)

-10

In [17]:
c = np.array([4, 5, 6])

In [19]:
np.dot(b, c)

-28

In [20]:
b * c

array([-12, -10,  -6])

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-3, -2, -1], [-6, -5, -4]])
A+B

array([[-2,  0,  2],
       [-2,  0,  2]])

In [22]:
3 * A

array([[ 3,  6,  9],
       [12, 15, 18]])

In [23]:
A * B

array([[ -3,  -4,  -3],
       [-24, -25, -24]])

In [24]:
np.dot(A, B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [25]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
np.dot(A.T, B)

array([[-27, -22, -17],
       [-36, -29, -22],
       [-45, -36, -27]])

In [30]:
A = np.array([[1, 2], [3, 4]])
b = np.array([-1, -2])
np.dot(A, b)

array([ -5, -11])

In [32]:
np.dot(b.T, A)

array([ -7, -10])

In [33]:
np.dot(b, A)

array([ -7, -10])

In [34]:
np.zeros(4)

array([0., 0., 0., 0.])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones(4) * 2

array([2., 2., 2., 2.])

In [38]:
np.arange(4)

array([0, 1, 2, 3])

In [39]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [40]:
np.arange(4, 10, 3)

array([4, 7])

In [41]:
np.zeros(6).reshape(2, 3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a = np.arange(10)
a[0]

0

In [44]:
a[-1]

9

In [45]:
a[1:5]

array([1, 2, 3, 4])

In [46]:
a[5:]

array([5, 6, 7, 8, 9])

In [47]:
a[:5]

array([0, 1, 2, 3, 4])

In [48]:
a[1:5:2]

array([1, 3])

In [49]:
a[1:5:3]

array([1, 4])

In [54]:
a[1:7:2]

array([1, 3, 5])

In [55]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [57]:
B = np.arange(1, 7).reshape(2, 3)
B

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
B[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
B[:2, 0]

array([1, 4])

In [60]:
B[:2, 2]

array([3, 6])

In [61]:
B[:2, ::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [62]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b

array([5, 7, 9])

In [63]:
a * b

array([ 4, 10, 18])

In [64]:
a = np.array([1, 2, 3])
b = 2
a + b

array([3, 4, 5])

In [65]:
a * b

array([2, 4, 6])

In [68]:
a = np.array([[1, 2], [3, 4]])
b = 2
a + b

array([[3, 4],
       [5, 6]])

In [69]:
a * b

array([[2, 4],
       [6, 8]])

In [70]:
c = np.array([5, 6])
a + c

array([[ 6,  8],
       [ 8, 10]])

In [71]:
a * c

array([[ 5, 12],
       [15, 24]])

In [73]:
a = np.array([1, 2, 3])
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [74]:
a[:, np.newaxis] * a

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])